#!/bin/bash

XVFB_WHD=${XVFB_WHD:-1024x768x16}

# Start Xvfb
Xvfb :100 -ac -screen 1 $XVFB_WHD +extension RANDR -nolisten tcp &
export xvfb=$!

# Set Display Variable
export DISPLAY=:100


# Start Firefox
firefox $@ &
export ffproc=$!


# Return terminal
/bin/bash