on: 
  push:
  pull_request:
  schedule:
  - cron: '0 19 * * *'
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.15.1, 1.15.2]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install docker   
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
        docker_nightly_version: snapshot-20201008
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test
      run: go test -v
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install docker   
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
        docker_nightly_version: snapshot-20201008
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 10
        max_attempts: 3
        retry_on: error
        command: go test -v