on: 
  push:
  pull_request:
  schedule:
  - cron: '0 19 * * *'
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.15.1, 1.15.2]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install docker   
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test
      run: go test -v